# --- GENERAL ---
spring.application.name=spring-secutiry-jwt
server.servlet.context-path=/admin/jwt/v1
server.port=9091
# --- H2 ---
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
complete.h2.path=${server.servlet.context-path}${spring.h2.console.path}
# --- JWT SECURITY ---
#256 bits long
jwt.secret=3KpV8g9X2Yz1Qw7LmN4rT5uHsA6bC0dEfGhIjKlMnOpQrStUvWxYz0123456789==
jwt.expiration=86400000
jwt.refresh-expiration-ms=604800000
